name:                B-Colorful-Lines
version:             0.1.0.0
github:              "githubuser/B-Colorful-Lines"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/B-Colorful-Lines#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- unordered-containers
- bytestring
- vector
- text

library:
  source-dirs: src

executables:
  B-Colorful-Lines-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - B-Colorful-Lines

tests:
  B-Colorful-Lines-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - B-Colorful-Lines
